"""The audit event vocabulary (Foundation Plan §07).

This enum names every event type the *full* design uses. Phase 1 only
ever emits a handful of these (TASK_CREATED, STATE_TRANSITION) — the rest
are declared now so later phases append to durable state through the same
typed vocabulary from day one, instead of inventing ad hoc string
constants per phase.
"""

from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    TASK_CREATED = "TASK_CREATED"
    STATE_TRANSITION = "STATE_TRANSITION"
    TOOL_REQUESTED = "TOOL_REQUESTED"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    OPERATION_STARTED = "OPERATION_STARTED"
    OPERATION_FINISHED = "OPERATION_FINISHED"
    RULES_LOADED = "RULES_LOADED"
    REPO_INSPECTED = "REPO_INSPECTED"
    BASELINE_RECORDED = "BASELINE_RECORDED"
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_ACCEPTED = "PLAN_ACCEPTED"
    WORKER_STARTED = "WORKER_STARTED"
    WORKER_HEARTBEAT = "WORKER_HEARTBEAT"
    FILE_READ = "FILE_READ"
    PATCH_APPLIED = "PATCH_APPLIED"
    PATCH_REJECTED = "PATCH_REJECTED"
    COMMAND_STARTED = "COMMAND_STARTED"
    COMMAND_FINISHED = "COMMAND_FINISHED"
    TEST_PASS = "TEST_PASS"
    TEST_FAIL = "TEST_FAIL"
    REPAIR_STARTED = "REPAIR_STARTED"
    REPAIR_FINISHED = "REPAIR_FINISHED"
    REVIEW_STARTED = "REVIEW_STARTED"
    REVIEW_FINDING = "REVIEW_FINDING"
    CHECKPOINT_CREATED = "CHECKPOINT_CREATED"
    CHECKPOINT_VALIDATED = "CHECKPOINT_VALIDATED"
    WORKER_LIMIT_APPROACHING = "WORKER_LIMIT_APPROACHING"
    WORKER_LIMITED = "WORKER_LIMITED"
    WORKER_HANDOFF_ISSUED = "WORKER_HANDOFF_ISSUED"
    WORKER_HANDOFF_ACCEPTED = "WORKER_HANDOFF_ACCEPTED"
    WORKER_RESUMED = "WORKER_RESUMED"
    WORKER_TRUST_CHANGED = "WORKER_TRUST_CHANGED"
    WORKER_CONFORMANCE_RUN_STARTED = "WORKER_CONFORMANCE_RUN_STARTED"
    WORKER_CONFORMANCE_RUN_FINALIZED = "WORKER_CONFORMANCE_RUN_FINALIZED"
    # Phase 7.5a: attributes one bounded worker turn's protocol/trust
    # decisions to worker_id/role/capability -- concepts ToolExecutor's
    # own TOOL_REQUESTED/POLICY_EVALUATED/OPERATION_STARTED/
    # OPERATION_FINISHED audit trail (unmodified) has no notion of. See
    # `workers.execution`'s module docstring.
    WORKER_TOOL_CALL_EVALUATED = "WORKER_TOOL_CALL_EVALUATED"
    WORKER_TURN_FINISHED = "WORKER_TURN_FINISHED"
    # Phase 7.5c: an isolated, disposable job worktree's own lifecycle
    # (`repo.job_worktree`) -- not scoped to any one task_id (a job
    # worktree may exist before any task is created against it), so
    # these are recorded with `task_id=None`, same as any other
    # system-level event with no task to attribute it to yet.
    JOB_WORKTREE_CREATED = "JOB_WORKTREE_CREATED"
    JOB_WORKTREE_RELEASED = "JOB_WORKTREE_RELEASED"
    LEASE_ACQUIRED = "LEASE_ACQUIRED"
    LEASE_RENEWED = "LEASE_RENEWED"
    LEASE_QUIESCING = "LEASE_QUIESCING"
    LEASE_EXPIRED = "LEASE_EXPIRED"
    LEASE_RELEASED = "LEASE_RELEASED"
    FENCE_STALE_REJECTED = "FENCE_STALE_REJECTED"
    ORPHAN_PROCESS_DETECTED = "ORPHAN_PROCESS_DETECTED"
    ORPHAN_PROCESS_TERMINATED = "ORPHAN_PROCESS_TERMINATED"
    ORPHAN_PROCESS_WAITED = "ORPHAN_PROCESS_WAITED"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_FINDING = "RECONCILIATION_FINDING"
    EXTERNAL_MODIFICATION_DETECTED = "EXTERNAL_MODIFICATION_DETECTED"
    POLICY_DENIED = "POLICY_DENIED"
    POLICY_APPROVAL_REQUIRED = "POLICY_APPROVAL_REQUIRED"
    CLOUD_ESCALATION_PACKAGE_BUILT = "CLOUD_ESCALATION_PACKAGE_BUILT"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_FAILED = "TASK_FAILED"
    TASK_COMPLETED = "TASK_COMPLETED"
