"""Production Baseline Security promotion: VALIDATION -> PRODUCTION (H.1).

## What this module is, and is not

This is the ONLY path by which a `worker_baseline_security_certificates`
row is ever written into the PRODUCTION database. It never runs the
Baseline Security evaluation harness itself (`security.evaluation`/
`security.live_certification` own that), never talks to a model, and
never accepts a client-supplied outcome, evidence_ref, certificate id,
digest, or fingerprint. It re-verifies an EXISTING `PASS` VALIDATION
certificate against the current live runtime and current durable
evidence, then durably carries that verdict forward into PRODUCTION by
calling `workers.security_baseline.record_baseline_certificate()` — the
same low-level recorder every other certificate path already uses. This
module never inserts into `worker_baseline_security_certificates`
directly and never duplicates that function's validation; it is not a
parallel authority path.

Promotion is role-independent, exactly like Baseline Security itself:
this module never reads, writes, or reasons about a Planner (or any
other role) certificate, and never touches `worker_trust_events` or
`permission_grants`. A promoted PRODUCTION Baseline Security certificate
is one of several INDEPENDENT inputs `workers.production_eligibility`
later combines (never merges) with a role certificate — promotion alone
grants no trust, no permission, and no role certificate to anyone.

## Fail-closed re-verification, not a copy

A VALIDATION `PASS` certificate is durable evidence of what a runtime
did *at evaluation time*. Promotion never assumes that is still true; it
independently re-establishes every fact production eligibility itself
would require, using the SAME machinery that already enforces it:

1. the live Ollama runtime is re-probed right now
   (`security.live_certification.verify_ollama_runtime`) against the
   server-owned, config-derived `expected` — a changed digest or
   runtime version since the VALIDATION run fails closed here, before
   any certificate is even looked up.
2. the CURRENT common runtime identity is rebuilt from that verified
   probe (`workers.security_baseline.runtime_profile_identity_from_config`)
   and must recompute to exactly `expected.expected_runtime_identity_fingerprint`
   — a stale or mismatching identity fails closed.
3. the most recent VALIDATION certificate whose OWN recorded runtime
   identity exactly `.matches()` that current identity is selected —
   never merely "the latest certificate for this worker" — mirroring
   `workers.production_eligibility`'s own no-wildcard binding. A newer,
   non-matching, or non-`PASS` certificate for the same profile is never
   silently skipped in favor of an older one.
4. that certificate must be `PASS` under the CURRENT `BASELINE_VERSION`
   — `FAIL`, `HARD_DISQUALIFIED`, or a policy-stale `PASS` all fail
   closed.
5. its durable evidence is reread and reverified
   (`security.evidence.read_baseline_security_evidence`) — missing,
   wrong-kind, hash-mismatched, or tampered evidence fails closed before
   anything is copied or recorded.
6. the live runtime is re-probed a SECOND time immediately before the
   write, closing the gap between evidence verification and the
   PRODUCTION write itself — mirrors `live_certification.
   certify_live_baseline_security`'s own pre-record re-probe.

Only once every one of those holds is the evidence document's exact
bytes copied into the PRODUCTION content store (content-addressed, so
the copy is independently re-verifiable from PRODUCTION alone) and
`record_baseline_certificate()` called against the PRODUCTION connection
with that SAME evidence_ref and the freshly-verified runtime profile.

## Idempotent, not duplicating

Certificates are append-only everywhere else in this codebase (see
`workers.security_baseline`'s own docstring), but "append-only" must
never mean "a repeated identical promotion mints a second, independent
authority row." Before writing anything, this module checks whether a
PRODUCTION certificate already exists whose
`promoted_from_validation_certificate_id` equals the EXACT VALIDATION
certificate's own `certificate_id` (schema v17) — not a comparison of
runtime identity or evidence content, a direct provenance link to the
one specific, already-durable VALIDATION row this promotion attempt
re-verified. That `certificate_id` is itself server-owned: it was
generated by `record_baseline_certificate()` when the VALIDATION
certificate was originally recorded (by the live certification path),
never supplied by a client. If a PRODUCTION certificate already claims
that exact provenance, it is returned as an idempotent success
(`ok=True`, `reason="already_promoted_to_production"`) and no new row,
no evidence copy, and no new audit event is created. This never
invalidates or overwrites a historical certificate, and never treats a
merely similar-looking prior promotion as the same authority. A
genuinely different, independently-issued VALIDATION certificate —
even one evaluated against the identical runtime — has its own,
different `certificate_id` and is therefore promoted as a normal new
row, exactly like any other re-certification.

Why provenance-by-certificate-id rather than a broader
`(worker_id, runtime_identity_fingerprint, evidence_ref)` uniqueness
invariant (an earlier revision of this module used exactly that): a
uniqueness invariant spanning ordinary columns constrains EVERY row in
`worker_baseline_security_certificates`, including plain VALIDATION
certificates that were never promoted and were never meant to be
constrained at all — VALIDATION recording has always been free to
create as many rows sharing a runtime identity and even, in principle,
identical evidence as evaluation produces, and neither the database
schema nor `record_baseline_certificate()` has ever forbidden that. A
broad invariant there would (a) risk failing a schema upgrade against
any database that already happens to hold duplicate historical triples
and (b) silently narrow VALIDATION semantics that H.1 was never asked
to change. `promoted_from_validation_certificate_id` sidesteps both:
it is `NULL` on every certificate this module did not itself write
(every VALIDATION certificate, and every historical row from before
this column existed), so a partial UNIQUE index on it — non-`NULL`
values only — constrains EXCLUSIVELY the rows this module produces,
touches no other row, and cannot fail against pre-existing data. See
migration 0017's own docstring for the schema-level detail.

The pre-check above alone is a sequential read-then-write guard: it is
what short-circuits the common case (a repeated or retried promotion
request) cheaply, before doing any further live probe or evidence
work, but by itself it cannot serialize two TRULY concurrent requests
that both read "not yet promoted" before either has written anything.
The actual safety guarantee against that race is the schema-level
partial UNIQUE index itself, not an application-level lock this module
manages. Once two concurrent requests both reach `record_baseline_
certificate()`'s own `BEGIN IMMEDIATE` write transaction, SQLite's
write lock already serializes their two INSERT attempts against each
other; the index is what makes the SECOND of those two serialized
attempts fail with `sqlite3.IntegrityError` instead of silently
succeeding as a duplicate authority row for the same VALIDATION
provenance. This module catches exactly that failure, re-reads the row
the other request just committed (by the same provenance lookup), and
returns it as the same `already_promoted_to_production` idempotent
success — never an unhandled error, and never a second audit event. No
database write lock is ever held across an Ollama network probe or
evidence verification: every such step happens before `record_
baseline_certificate()` is called, and that function's own transaction
is already the shortest possible atomic section (just the INSERT and
its audit event).

## No client-supplied authority

Every value this module reasons about — `expected` (server-owned config,
never HTTP input; see `BaselineCertificationTarget`), the VALIDATION
certificate, and the reread evidence document — is either backend-owned
configuration or durable evidence this module itself re-verifies. The
WebUI action that triggers this accepts `worker_id` only as a resource
path (identifying WHICH already-registered worker to promote, exactly
like every other Certification Center route) and an empty JSON body —
no outcome, evidence_ref, certificate_id, digest, or fingerprint is ever
a caller-supplied parameter here.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from pathlib import Path

from code_slayer.audit.events import EventType
from code_slayer.audit.writer import AuditWriter
from code_slayer.security.evidence import (
    EVIDENCE_KIND,
    SecurityEvaluationEvidenceError,
    read_baseline_security_evidence,
)
from code_slayer.security.live_certification import (
    LiveOllamaRuntimeExpectation,
    verify_ollama_runtime,
)
from code_slayer.store.baseline_security_certificates_repo import (
    BaselineSecurityCertificatesRepo,
)
from code_slayer.store.content_store import ContentStore
from code_slayer.store.db import utcnow_iso
from code_slayer.store.workers_repo import WorkersRepo
from code_slayer.workers.security_baseline import (
    BASELINE_VERSION,
    RuntimeProfileIdentity,
    SecurityBaselineOutcome,
    record_baseline_certificate,
    runtime_profile_binding_from_stored,
    runtime_profile_identity_from_config,
)

ENVIRONMENT_PRODUCTION = "PRODUCTION"


@dataclass(frozen=True)
class ProductionPromotionResult:
    """Bounded result of one promotion attempt. Never carries raw model
    text, secrets, or HTTP bodies — mirrors `LiveSecurityCertificationResult`."""

    ok: bool
    reason: str
    runtime_identity_fingerprint: str | None = None
    validation_certificate_id: str | None = None
    production_certificate_id: str | None = None
    evidence_ref: str | None = None


def _deny(reason: str, **kwargs) -> ProductionPromotionResult:
    return ProductionPromotionResult(False, reason, **kwargs)


def _latest_matching_certificate(certificates, runtime_profile: RuntimeProfileIdentity):
    """The first (most recent, by the repo's own `issued_at DESC` order)
    certificate whose OWN recorded runtime identity exactly `.matches()`
    `runtime_profile` — never a wildcard, never "any certificate for this
    worker." Mirrors `workers.production_eligibility`'s own matching
    helper exactly (that helper is module-private there; this is the
    same rule, not a divergent reimplementation)."""
    for certificate in certificates:
        stored = runtime_profile_binding_from_stored(
            model_tag=certificate.model_tag,
            model_digest=certificate.model_digest,
            endpoint=certificate.endpoint,
            runtime_version=certificate.runtime_version,
            normalizer_id=certificate.normalizer_id,
            normalizer_version=certificate.normalizer_version,
            runtime_config_fingerprint=certificate.runtime_config_fingerprint,
            runtime_identity_fingerprint=certificate.runtime_identity_fingerprint,
        )
        if stored.matches(runtime_profile):
            return certificate
    return None


@dataclass(frozen=True)
class PromotionAvailability:
    """Backend-authoritative, durable-state-only projection of whether
    promotion would currently succeed. See `describe_promotion_availability`.
    Never carries raw model text, secrets, or HTTP bodies."""

    available: bool
    reason: str
    runtime_identity_fingerprint: str | None = None
    validation_certificate_id: str | None = None
    production_certificate_id: str | None = None


def describe_promotion_availability(
    validation_conn: sqlite3.Connection,
    production_conn: sqlite3.Connection,
    *,
    worker_id: str,
    expected: LiveOllamaRuntimeExpectation,
) -> PromotionAvailability:
    """The ONE backend-authoritative source the WebUI reads to decide
    whether to offer the promotion action. This is a DISPLAY projection
    only, computed entirely from already-durable state and the
    server-owned expected config -- it never probes live Ollama (GET
    routes in this codebase never make a live network call; mirrors
    `CertificationService._runtime_status`'s and `_baseline_status`'s
    own "config-bound, not live-probed" precedent). Consequently a
    `True` here is advisory, not a guarantee: `promote_baseline_
    security_to_production()` independently re-verifies everything live
    and remains the only authoritative decision -- exactly the same
    relationship `ready_for_certification` already has to an actual
    certification run.

    Reason vocabulary intentionally matches `promote_baseline_security_
    to_production()`'s own deny reasons (`no_validation_certificate`,
    `validation_certificate_not_pass`, `already_promoted_to_production`,
    ...) so a frontend or operator never has to learn two vocabularies
    for the same underlying gate. The frontend MUST treat this as the
    sole source of promotability -- it must never independently infer
    availability from `baseline_security.status`, run/busy state, or any
    other client-side heuristic.

    Unlike `promote_baseline_security_to_production()`, this does not
    require a VALIDATION `workers` row to already exist (that row is a
    lazy mirror of PRODUCTION registration -- see `CertificationService.
    _ensure_validation_worker` -- created on first preflight/run, not a
    read-time side effect this display projection should ever perform).
    A worker that is PRODUCTION-registered but has never had a
    VALIDATION run naturally has no certificates, which already reports
    `no_validation_certificate` below -- exactly mirroring `_baseline_
    status`'s own precedent of querying certificates directly rather
    than gating on that row."""
    if WorkersRepo(production_conn).get(worker_id) is None:
        return PromotionAvailability(False, "unknown_worker")

    try:
        runtime_profile = runtime_profile_identity_from_config(
            model_tag=expected.model_tag,
            model_digest=expected.model_digest,
            endpoint=expected.openai_base_url,
            runtime_version=expected.runtime_version,
            effective_context_tokens=expected.effective_context_tokens,
            temperature=float(expected.temperature),
            normalizer_id=expected.normalizer_id,
            normalizer_version=expected.normalizer_version,
        )
    except (TypeError, ValueError):
        return PromotionAvailability(False, "insufficient_runtime_profile_identity")

    fingerprint = runtime_profile.runtime_identity_fingerprint
    if fingerprint != expected.expected_runtime_identity_fingerprint:
        return PromotionAvailability(
            False, "runtime_identity_fingerprint_mismatch",
            runtime_identity_fingerprint=fingerprint,
        )

    certificates = BaselineSecurityCertificatesRepo(validation_conn).list_for_worker(worker_id)
    if not certificates:
        return PromotionAvailability(
            False, "no_validation_certificate", runtime_identity_fingerprint=fingerprint,
        )
    certificate = _latest_matching_certificate(certificates, runtime_profile)
    if certificate is None:
        return PromotionAvailability(
            False, "validation_certificate_profile_mismatch",
            runtime_identity_fingerprint=fingerprint,
        )
    if certificate.baseline_version != BASELINE_VERSION:
        return PromotionAvailability(
            False, "validation_certificate_baseline_version_stale",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
        )
    if certificate.outcome != SecurityBaselineOutcome.PASS.value:
        return PromotionAvailability(
            False, "validation_certificate_not_pass",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
        )

    already_promoted = BaselineSecurityCertificatesRepo(
        production_conn,
    ).get_by_promotion_provenance(certificate.certificate_id)
    if already_promoted is not None:
        return PromotionAvailability(
            False, "already_promoted_to_production",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
            production_certificate_id=already_promoted.certificate_id,
        )

    return PromotionAvailability(
        True, "promotable",
        runtime_identity_fingerprint=fingerprint,
        validation_certificate_id=certificate.certificate_id,
    )


def promote_baseline_security_to_production(
    validation_conn: sqlite3.Connection,
    production_conn: sqlite3.Connection,
    *,
    worker_id: str,
    validation_blobs_dir: Path | str,
    production_blobs_dir: Path | str,
    expected: LiveOllamaRuntimeExpectation,
    now_fn=utcnow_iso,
) -> ProductionPromotionResult:
    """Re-verify and durably carry forward one `PASS` VALIDATION Baseline
    Security certificate into PRODUCTION. See the module docstring for
    the complete, ordered fail-closed check list. Never mutates
    `worker_trust_events`, `permission_grants`, or any role-certificate
    table; never records more than one new PRODUCTION
    `worker_baseline_security_certificates` row per distinct VALIDATION
    `certificate_id` -- a repeat promotion of the exact same VALIDATION
    certificate returns the existing row instead (see "Idempotent, not
    duplicating").
    """
    if not isinstance(worker_id, str) or not worker_id:
        return _deny("malformed_promotion_request")
    if not isinstance(expected, LiveOllamaRuntimeExpectation):
        return _deny("malformed_promotion_request")
    if (
        not isinstance(validation_blobs_dir, (str, Path))
        or not str(validation_blobs_dir).strip()
        or not isinstance(production_blobs_dir, (str, Path))
        or not str(production_blobs_dir).strip()
    ):
        return _deny("missing_durable_security_evidence")
    if WorkersRepo(production_conn).get(worker_id) is None:
        return _deny("unknown_worker")
    if WorkersRepo(validation_conn).get(worker_id) is None:
        return _deny("unknown_worker")

    try:
        runtime_version, model_digest = verify_ollama_runtime(expected)
    except ValueError as exc:
        reason = str(exc) if str(exc) else "runtime_probe_unavailable"
        return _deny(reason)

    try:
        runtime_profile = runtime_profile_identity_from_config(
            model_tag=expected.model_tag,
            model_digest=model_digest,
            endpoint=expected.openai_base_url,
            runtime_version=runtime_version,
            effective_context_tokens=expected.effective_context_tokens,
            temperature=float(expected.temperature),
            normalizer_id=expected.normalizer_id,
            normalizer_version=expected.normalizer_version,
        )
    except (TypeError, ValueError):
        return _deny("insufficient_runtime_profile_identity")

    fingerprint = runtime_profile.runtime_identity_fingerprint
    if fingerprint != expected.expected_runtime_identity_fingerprint:
        return _deny(
            "runtime_identity_fingerprint_mismatch",
            runtime_identity_fingerprint=fingerprint,
        )

    certificates = BaselineSecurityCertificatesRepo(validation_conn).list_for_worker(worker_id)
    if not certificates:
        return _deny(
            "no_validation_certificate",
            runtime_identity_fingerprint=fingerprint,
        )
    certificate = _latest_matching_certificate(certificates, runtime_profile)
    if certificate is None:
        return _deny(
            "validation_certificate_profile_mismatch",
            runtime_identity_fingerprint=fingerprint,
        )
    if certificate.baseline_version != BASELINE_VERSION:
        return _deny(
            "validation_certificate_baseline_version_stale",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
        )
    if certificate.outcome != SecurityBaselineOutcome.PASS.value:
        return _deny(
            "validation_certificate_not_pass",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
        )

    # Idempotency: a PRODUCTION certificate already recorded with this
    # EXACT VALIDATION certificate as its provenance is the same
    # authority this request would otherwise mint again. Return it
    # as-is; write nothing new. See the module docstring's "Idempotent,
    # not duplicating".
    already_promoted = BaselineSecurityCertificatesRepo(
        production_conn,
    ).get_by_promotion_provenance(certificate.certificate_id)
    if already_promoted is not None:
        return ProductionPromotionResult(
            True,
            "already_promoted_to_production",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
            production_certificate_id=already_promoted.certificate_id,
            evidence_ref=already_promoted.evidence_ref,
        )

    try:
        document = read_baseline_security_evidence(
            validation_conn,
            validation_blobs_dir,
            certificate.evidence_ref,
            expected_runtime_identity_fingerprint=fingerprint,
        )
    except SecurityEvaluationEvidenceError as exc:
        return _deny(
            exc.reason,
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
        )
    if document.get("worker_id") != worker_id:
        return _deny(
            "evidence_worker_mismatch",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
        )

    # Close the gap between evidence verification and the PRODUCTION
    # write: re-probe live Ollama once more, mirroring
    # `live_certification.certify_live_baseline_security`'s own
    # pre-record re-probe.
    try:
        verify_ollama_runtime(expected)
    except ValueError:
        return _deny(
            "runtime_changed_since_validation",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
        )

    try:
        validation_store = ContentStore(validation_conn, validation_blobs_dir)
        evidence_bytes = validation_store.read(certificate.evidence_ref)
    except KeyError:
        return _deny(
            "missing_durable_security_evidence",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
        )

    production_store = ContentStore(production_conn, production_blobs_dir)
    copied = production_store.put(
        evidence_bytes,
        media_type="application/json",
        source_kind=EVIDENCE_KIND,
        exportable=False,
    )
    if copied.content_hash != certificate.evidence_ref:
        return _deny(
            "durable_security_evidence_hash_mismatch",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
        )

    # Reread and reverify from PRODUCTION alone -- the copy must be
    # independently trustworthy from the PRODUCTION side, not merely
    # byte-identical at write time.
    try:
        read_baseline_security_evidence(
            production_conn,
            production_blobs_dir,
            certificate.evidence_ref,
            expected_runtime_identity_fingerprint=fingerprint,
        )
    except SecurityEvaluationEvidenceError as exc:
        return _deny(
            exc.reason,
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
            evidence_ref=certificate.evidence_ref,
        )

    # Final atomic section: the sequential check above already handles
    # the common case (a repeated, non-concurrent promotion request),
    # but two TRULY concurrent requests can both pass it before either
    # has written anything. `record_baseline_certificate()` opens its
    # own short `BEGIN IMMEDIATE` write transaction for exactly the
    # INSERT (+ audit event) below -- no network probe or evidence
    # verification ever runs while that lock is held; all of that
    # already happened above. SQLite's write lock alone already
    # serializes two concurrent INSERT attempts against each other; the
    # `ux_worker_baseline_security_certificates_promotion_provenance`
    # partial unique index (schema v17) is what makes the SECOND of
    # those two serialized attempts fail deterministically instead of
    # silently succeeding as a duplicate authority row -- see that
    # migration's own docstring. A failure here is resolved to the row
    # the OTHER concurrent request just committed, never treated as an
    # unexplained error.
    try:
        recorded = record_baseline_certificate(
            production_conn,
            worker_id=worker_id,
            runtime_profile=runtime_profile,
            outcome=SecurityBaselineOutcome.PASS,
            evidence_ref=certificate.evidence_ref,
            reason="promoted_from_validation",
            hard_disqualifiers=(),
            now_fn=now_fn,
            promoted_from_validation_certificate_id=certificate.certificate_id,
        )
    except sqlite3.IntegrityError:
        winner = BaselineSecurityCertificatesRepo(
            production_conn,
        ).get_by_promotion_provenance(certificate.certificate_id)
        if winner is None:
            # The partial unique index exists on exactly this one
            # column; a violation that does NOT resolve to a matching
            # row here is not this invariant and must never be
            # silently absorbed.
            raise
        return ProductionPromotionResult(
            True,
            "already_promoted_to_production",
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
            production_certificate_id=winner.certificate_id,
            evidence_ref=winner.evidence_ref,
        )
    if not recorded.ok or recorded.certificate is None:
        return _deny(
            recorded.reason,
            runtime_identity_fingerprint=fingerprint,
            validation_certificate_id=certificate.certificate_id,
            evidence_ref=certificate.evidence_ref,
        )

    AuditWriter(production_conn).append(
        task_id=None,
        event_type=EventType.SECURITY_BASELINE_CERTIFICATE_PROMOTED_TO_PRODUCTION,
        actor_type="system",
        actor_id=worker_id,
        payload={
            "worker_id": worker_id,
            "validation_certificate_id": certificate.certificate_id,
            "production_certificate_id": recorded.certificate.certificate_id,
            "runtime_identity_fingerprint": fingerprint,
            "evidence_ref": certificate.evidence_ref,
        },
    )

    return ProductionPromotionResult(
        True,
        "promoted_to_production",
        runtime_identity_fingerprint=fingerprint,
        validation_certificate_id=certificate.certificate_id,
        production_certificate_id=recorded.certificate.certificate_id,
        evidence_ref=certificate.evidence_ref,
    )
